### PR TITLE
Fix issue #52 Skat table hangs if AI player plays schwarz in first trick

### PR DESCRIPTION
**Pull request by b0n541**

### CODE REVIEW

**Comment by mlrdev** [comment]
```org.jskat.player.JSkatPlayer.Loser```
Seems to be a typo^^

**Comment by b0n541** [comment]
I'm not really sure what you are talking about?

**Comment by mlrdev** [comment]
You're right. Have missed the correct line with my thumb ;-).

It's ```RamschSkatOwner.Loser``` that looks a bit odd.

**Comment by b0n541** [comment]
O.k. the naming could be improved. It's an setting to which player the points of a skat go after a Ramsch game was finished.

**Pull request merged**
