### PR TITLE
Enhancement/7 show when ai player is thinking

### PR DESCRIPTION
**Pull request by mlrdev**
Adds an hourglass to the hand panel, if the panel is of an opponent.

The hourglass icon was taken from here:
 http://www.flaticon.com/free-icon/hourglass-with-sand_16326
and is free to use if the author is mentioned as the autor of this icon within jskats credits section.
Feel free to replace the icon with any icon that works better for your project.

### CODE REVIEW

**Comment by b0n541** [comment]
We could also use this icon from the Tango project:

https://commons.wikimedia.org/wiki/File:Gnome-system-run.svg

**Comment by mlrdev** [comment]
I've updated the icon and slightly changed the behavior to only display the icon if the player is NN.
It works now on either table position :-).

**Comment by b0n541** [comment]
I did some changes. Please have a look. I need to test it while playing on the ISS too.

**Comment by mlrdev** [comment]
Looks better now, except that it was a bit confusing why it's displayed where it is displayed.
Now that I am aware of the _IconPanel_ I understand why you display it there in favour to have the icons on their own position rather than to prance around when one of the others (chatLabel, readyToPlayLabel, resignedLabel) is active as well.

**Comment by b0n541** [comment]
There is still room for improvement to align all icons to the right and not have empty space for disabled icons...

**Pull request merged**
